### ISSUE TITLE
Mturk advice: group_by_arrival_time

### ISSUE THREAD

**Issue by AlexHartveld** [AlexHartveld/otree-costs-of-control-questionnaire-mturk#13]
https://otree.readthedocs.io/en/latest/multiplayer/waitpages.html#wait-pages

> A typical way to use group_by_arrival_time is to put it after an app that filters out participants. For example, if your session has a consent page that gives participants the chance to opt out of the study, you can make a “consent” app that just contains the consent pages, and then have an app_sequence like ['consent', 'my_game'], where my_game uses group_by_arrival_time. This means that if someone opts out in consent, they will be excluded from the grouping in my_game.

**Comment by NicoDiePlume** [comment]
- instructions are also apps now
- group by arrival time once they answered the questions about instructions
- players initially are all group 1 with id_in_group just 1,2,3,4,5,6,7,... and once they get matched they are assigned to group 2,3,4... with id_in_group 1 and 2 only (maybe important for analysis to sort some participants out)
