### ISSUE TITLE
Feedback on Game 2:

### ISSUE THREAD

**Issue by AlexHartveld** [AlexHartveld/otree-costs-of-control-questionnaire-mturk#16]
1. It is not clear if player A loses points for every slider. 
2. The time limit turns it into a game where I want to finish all before the time runs out. Why is there a time limit?
3. How is the minimum amount enforced? Can we make this clearer? 
4. We should include the above point in the comprehension part. 
5. Design in general, Java will get in touch.

**Comment by NicoDiePlume** [comment]
@AlexHartveld 
2. Time limit is there so that the other Player does not have to wait so long since they only see a wait page in between. 
3. Minimum amount is enforced via text and that they cannot actually go to the next page without satisfying the "move at least X sliders" requirement.

**Comment by NicoDiePlume** [comment]
Instructions have been adapted according to what Alex and Java suggested. Payouts are updated. Timelimit is removed and instead waiting page got adapted.
